default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432


development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  url: <%= ENV['POSTGRES_URL'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: ruby_intern_test

production:
  primary: &primary_production
    <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  url: <%= ENV['POSTGRES_URL'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  cache:
    <<: *primary_production
    database: ruby_intern_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: ruby_intern_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: ruby_intern_production_cable
    migrations_paths: db/cable_migrate
